### ISSUE TITLE
Error when rendering sitemap.xml

### ISSUE THREAD

**Issue by benjaminu** [bolt/Sitemap#16]
Using `strict_variables` set to `true`, I get the following warning when I try to load `/sitemap.xml`.
```
Warning: Key "alt" for array with keys "file" does not exist in "assets/sitemap_xml.twig" at line 25 #0 /websites/bolt1/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(91): Twig_Template->getAttribute(Array, 'alt', Array) #1 /websites/bolt1/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_123c1abff86fa216361224d9a5742509575092be54e4acd1d46241af86f4ece6->doDisplay(Array, Array) #2 /websites/bolt1/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #3 /websites/bolt1/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) #4 /websites/bolt1/src/Response/BoltResponse.php(187): Twig_Template->render(Array) #5 /websites/bolt1/src/Response/BoltResponse.php(166): Bolt\Response\BoltResponse->compile() #6 /websites/bolt1/src/Response/BoltResponse.php(152): Bolt\Response\BoltResponse->getContent() #7 /Users/benjam in /websites/bolt1/src/Response/BoltResponse.php on line 201
Key "alt" for array with keys "file" does not exist
```

**Comment by GawainLynch** [comment]
Fixed in #15 & 80408a9917fef566bcaab3e384cc34477651fb90

Released 1.0.6 just now
